name: deploy
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'gatsby*'
      - ".github/workflows/deploy.yml"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and checkout.
        uses: actions/checkout@v2

      - name: Setup Node and NPM.
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies and build website.
        env:
          GRAPHQL_GITHUB_TOKEN: ${{ secrets.GRAPHQL_GITHUB_TOKEN }}
        run: npm install && npm run build -- --prefix-paths

      - name: Deploy to AWS.
        uses: lycuid/aws_deploy@master
        with:
          TARGET: ${{ format('{0}/{1}', github.workspace, 'public') }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          EC2_REMOTE_PATH: ${{ secrets.EC2_REMOTE_PATH }}
          S3_BUCKET_PATH: ${{ format('s3://{0}', secrets.S3_ASSETS_BUCKET) }}
