name: pages
on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "gatsby*"
      - ".github/workflows/deploy.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and checkout.
        uses: actions/checkout@v2
      - name: Setup Node and NPM.
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies and build website.
        env:
          GRAPHQL_GITHUB_TOKEN: ${{ secrets.GRAPHQL_GITHUB_TOKEN }}
        run: npm install && npm run build -- --prefix-paths

  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
